spring:
  datasource:
    ipinfo:
      driverClassName: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.0.11:3306/dgg
      username: dgg
      password: dgg
      druid :
        init-method: select 1 from dual
        web-stat-filter :
          enabled: true
        stat-view-servlet:
          url-pattern: /druid/*
          reset-enable: 
          login-username: admin
          login-password: admin
          allow: 
          deny: 
    auth:
      driverClassName: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.0.11:3306/dgg_auth
      username: dgg
      password: dgg
      druid :
        init-method: select 1 from dual
        web-stat-filter :
          enabled: true
        stat-view-servlet:
          url-pattern: /druid_auth/*
          reset-enable: 
          login-username: admin
          login-password: admin
          allow: 
          deny:
logging:
  config: classpath:logback-dev.xml

